# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
   # 修改成專案名稱    
    - name: Publish .NET Core Project
      run: dotnet publish VscodeBlazor.csproj -c Release -o release --nologo
      
    # 修改 index.html 的 base href 設定
    - name: 修改 index.html 的 base href 設定
      run: sed -i 's/<base href="\/" \/>/<base href="\/VscodeBlazor\/" \/>/g' release/wwwroot/index.html
        
    - name: 新增 .nojekyll 檔
      run: touch wwwroot/.nojekyll
      
    # 複製 index.html 成 404.html
    - name: 複製 index.html 成 404.html
      run: cp wwwroot/index.html /wwwroot/404.html
      
    - name: Commit wwwroot to GitHub Pages
      uses: a709743380/github-pages-deploy-action@v7.0.0
      with:
          BRANCH: gh-pages
          FOLDER: release/wwwroot
