name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
      
    - name: Publish .NET Core Project
      run: dotnet publish VscodeBlazor.csproj -c Release -o release --nologo
      
    - name: Finish
      run: echo "dotnet publish VscodeBlazor.csproj -c Release -o release --nologo"
      
    - name: Modify base href in index.html
      run: sed -i 's/<base href="\/" \/>/<base href="\/VscodeBlazor\/" \/>/g' release/wwwroot/index.html
        
    - name: Create .nojekyll file
      run: touch wwwroot/.nojekyll
      
    - name: Copy index.html to 404.html
      run: cp wwwroot/index.html wwwroot/404.html
      
    - name: Commit wwwroot to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./release/wwwroot
